#!/bin/sh
# properties = {"local": false, "rule": "combine_strelka_vcfs", "input": ["/scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.indels.pass.vcf.gz", "/scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.snvs.vcf.gz", "/scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.snvs.pass.vcf.gz", "/scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.indels.vcf.gz"], "threads": 1, "cluster": {}, "jobid": 40, "params": {}, "resources": {}, "output": ["/scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.pass.vcf", "/scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.vcf"]}
cd /home/eknodel/SCC_samples/Parent_cell_lines/03_variant_annotation && \
/home/eknodel/miniconda3/envs/var_call_env/bin/python -m snakemake /scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.pass.vcf /scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.vcf --snakefile /home/eknodel/SCC_samples/Parent_cell_lines/03_variant_annotation/VEP_PVACseq_updated.snakefile \
--force -j --keep-target-files --keep-shadow --keep-remote \
--wait-for-files /scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.indels.pass.vcf.gz /scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.snvs.vcf.gz /scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.snvs.pass.vcf.gz /scratch/eknodel/SCC_samples/Parent_cell_lines/strelka/185_1_SC_09_G9_304_273_S6_L003/results/variants/somatic.indels.vcf.gz /home/eknodel/SCC_samples/Parent_cell_lines/03_variant_annotation/.snakemake/tmp.7_x0swwz --latency-wait 5 \
--benchmark-repeats 1 \
--force-use-threads --wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
   --nocolor \
--notemp --quiet --no-hooks --nolock --force-use-threads  --allowed-rules combine_strelka_vcfs  && touch "/home/eknodel/SCC_samples/Parent_cell_lines/03_variant_annotation/.snakemake/tmp.7_x0swwz/40.jobfinished" || (touch "/home/eknodel/SCC_samples/Parent_cell_lines/03_variant_annotation/.snakemake/tmp.7_x0swwz/40.jobfailed"; exit 1)

